{
    'name': "KG NABIDH",
    'version': '17.0.0.1',
    'depends': ['bista_tdcc_operations', 'base'],
    'author': "Klystron Gobal",
    'maintainer': "Bebisha",
    'category': "Category",
    'sequence': -98,
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_number.xml',
        'views/menu_views.xml',
        'views/partner_views.xml',
        'views/conf_setting_views.xml',
        'views/address_type_views.xml',
        'views/specimen_type_modifier_views.xml',
        'views/segment_social_history_views.xml',
        'views/allergy_information_views.xml',
        'views/patient_identification_views.xml',
        'views/associated_parties_views.xml',
        'views/diagnosis_information_views.xml',
        'views/guarantor_views.xml',
        'views/observation_views.xml',
        'views/segment_family_history_views.xml',
        'views/insurence_views.xml',
        'views/patient_visit_views.xml',
        'views/procedures_segment_views.xml',
        'views/relationship_views.xml',
        'views/gender_views.xml',
        'views/marital_status_views.xml',
        'views/ethinic_views.xml',
        'views/race_views.xml',
        'views/religion_views.xml',
        'views/admision_type_views.xml',
        'views/admit_source_views.xml',
        'views/discharge_disposition_views.xml',
        'views/hospital_service_views.xml',
        'views/patient_class_views.xml',
        'views/diagnosis_type_views.xml',
        'views/abnormal_flag_views.xml',
        'views/result_status_code_views.xml',
        'views/confidentiality_code_views.xml',
        'views/diagnosis_service_views.xml',
        'views/rout_views.xml',
        'views/admin_site.xml',
        'views/document_available_status_views.xml',
        'views/document_status_views.xml',
        'views/treatment_refusal_views.xml',
        'views/completion_status_views.xml',
        'views/order_status_views.xml',
        'views/common_oder_views.xml',
        'views/order_type_views.xml',
        'views/order_control_views.xml',
        'views/result_code_views.xml',
        'views/nationality_views.xml',
        'views/religion_views.xml',
        'views/value_type_views.xml',
        'views/observation_views.xml',
        'views/pharmacy_order_views.xml',
        'views/country_views.xml',
        'views/priority_views.xml',
        'views/problem_views.xml',
        'views/allergen_type_code_views.xml',
        'views/allergen_code_mnemonic_description_views.xml',
        'views/guarantor_relationship_views.xml',
        'views/document_type_views.xml',
        'views/document_confidential_status_views.xml',
        'views/specimen_type_views.xml',
        'views/specimen_type_views.xml',
        'views/contact_role_views.xml',
        'views/allergy_severty_code_views.xml',
        'views/allergy_reaction_code_views.xml',
        'views/primary_language_views.xml',
        'views/appointment_appointment_views.xml',
        'views/message_type_views.xml',
        'views/nabidh_log_views.xml',
        'views/z_segment_consent.xml',
        'views/unit_views.xml',
        'views/social_habit_cat_views.xml',
        'views/social_habit_views.xml',
        'views/patient_profession_views.xml',
        'views/state_views.xml',
        'views/transcription_ocument_header_views.xml',
        'views/document_completion_status_views.xml',
        'views/problem_life_cycle_status_views.xml',
        'views/observation_request_views.xml',
        'wizard/merge_confirmation_wizard_views.xml',

        'wizard/merge_patient_views.xml',

    ],

}
