from . import account_move
from . import account_bank_statement_line
from . import budget
from . import account_analytic_account
from . import account_move_line
from . import res_partner_bank
from . import res_company
from . import res_config
from . import res_users
from . import account_analytic_line
