{
    "name": "Klystron Base API",
    "version": "17.0.1.0.0",
    "category": "API",
    'license': 'AGPL-3',
    "author": "Anal Joy",
    "website": "www.klystronglobal.com",
    "summary": "Klystron Base API",
    "support": "ajepebabatope@gmail.com",
    "description": """Common connector for external API requests.""",
    "depends": ["base", "stock", "account", 'sale', 'project', 'hr', 'hr_holidays', 'kg_hr_employee',
                'kg_push_notification', 'kg_itron_timesheet', 'hr_expense', ],
    "data": [
        "data/data.xml",
        "data/scheduled_attendance_email.xml",
        "views/ir_model.xml", "views/res_users.xml",
        "security/ir.model.access.csv",
        "views/project.xml",
        "views/hr_leave_views.xml",
        "views/res_config_settings.xml",
             ],
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
}
