from . import hr_employee
from . import sponsor
from . import hr_contract
from . import hr_leave_allocation
from . import hr_payslip
from . import hr_employee_entry
from . import hr_sign_on_off
from . import discharge_eligibility
from . import hr_shop_entry
from . import pending_salary
from . import hr_payslip_worked_days
from . import hr_salary_rule
from . import hr_discharge
