# -*- coding: utf-8 -*-
{
    'name': 'KG Raw Fisheries HRMS',
    'version': '17.0',
    'summary': 'Raw Fisheries ERP',
    'description': 'Enterprise Odoo ERP Implementation for Raw Fisheries',
    'category': 'Other',
    'author': 'KG',
    'license': 'AGPL-3',
    'website': 'www.klystronglobal.com',
    'depends': ['base', 'hr', 'hr_contract', 'hr_payroll', 'stock', 'account', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'security/secruity_goups.xml',

        'data/cron.xml',
        'data/hr_payroll_data.xml',
        'data/hr_salary_rule.xml',
        'data/ir_sequence.xml',

        'reports/resigned_employees_report.xml',
        'reports/leave_application_form.xml',
        'reports/employee_entry_report.xml',
        'reports/shop_entry_report.xml',
        'reports/discharge_entry_report.xml',
        'reports/report.xml',

        'wizard/hr_payroll_payslips_by_employees_views.xml',
        'wizard/employee_entry_wizard_views.xml',
        'wizard/shop_entry_wizard_views.xml',
        'wizard/discharge_entry_wizard_views.xml',
        'wizard/entry_report_views.xml',
        'wizard/shop_entry_report_wizard_views.xml',
        'wizard/discharge_entry_report_wizard_views.xml',
        'wizard/sign_on_off_wizard_views.xml',
        'wizard/ps_reject_reason_wizard.xml',

        'views/hr_employee.xml',
        'views/hr_contract.xml',
        'views/hr_payslip.xml',
        'views/sponsor.xml',
        'views/resigned_employees.xml',
        'views/hr_employee_entry_views.xml',
        'views/hr_sign_on_off_views.xml',
        'views/discharge_eligibility_views.xml',
        'views/hr_shop_entry_views.xml',
        'views/res_partner_views.xml',
        'views/report_payslip_templates.xml',
        'views/hr_salary_rule_views.xml',
        'views/hr_discharge_views.xml',
        'views/pending_salary_views.xml',
        'views/hr_leave.xml',
        'views/menu.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': False,

}
