{
    'name': 'KG Ultracare Accounting',
    'version': '17.0.0.0.0',
    'category': 'Extra Tools',
    'summary': 'KG',
    'sequence': '10',
    'license': 'AGPL-3',
    'author': 'Anal Joy',
    'maintainer': 'KG',
    'website': 'www.klystronglobal.com',
    'depends': ['base', 'account', 'account_accountant', 'account_online_synchronization', 'account_reports'],
    'data': [
        'security/ir.model.access.csv',
        # 'views/aged_partner_balance_inherit.xml',
       'report/account_ledger_report.xml'
       'report/account_receivable_ledger_report.xml'
        'wizard/unpaid_invoice_wizard.xml',
        'wizard/purchase_bill_register_wizard.xml',
        'wizard/debtors_status_wizard.xml',
        'wizard/bank_book_wizard.xml',
        'wizard/creditors_status_wizard.xml',
        'wizard/account_ledger_wizard.xml',
        'wizard/account_receivable_ledger_wizard.xml',
        'wizard/consolidated_aging_analysis_receivables_wizard.xml',
        'wizard/balance_sheet_schedule_wizard.xml',
        'wizard/bank_payment_register_wizard.xml',
        'wizard/bank_status_wizard.xml',
        'wizard/cash_receipts_register_wizard.xml',
        'wizard/cash_book_wizard.xml',
        'wizard/consolidated_account_ledger_wizard.xml',
        'wizard/cash_payments_register_wizard.xml',
        'wizard/bank_reconciliation_wizard.xml',
        'wizard/pdc_checklist_wizard.xml',
        'wizard/pdc_issue_register_wizard.xml',
        'wizard/pdc_receipt_register_wizard.xml',
        'wizard/pdc_maturity_wizard.xml',
        'wizard/pdc_outstanding_wizard.xml',
        'wizard/ac_aging_analysis_wizard.xml',
        'wizard/opening_balance_wizard.xml',
        'wizard/expense_purchase_summary_wizard.xml',
        'wizard/debit_notes_register_wizard.xml',
        'wizard/detailed_expense_wizard.xml',
        'wizard/income_statement_wizard.xml',
        'wizard/job_costing_wizard.xml',
        'wizard/missing_bank_receipts_wizard.xml',
        'wizard/petty_cash_book_wizard.xml',

        'views/account_account.xml',
        'views/approval_type.xml',
        'views/account_payment.xml',
        'views/account_move.xml',
        'views/account_online_link.xml',
        'views/account_payment_terms.xml',

    ],
    # 'images': ['static/description/icon.png'],
    'installable': True,
    'application': False,
    'auto_install': False,

}
