{
    'name': 'Sales Subscription',
    'version': '17.0.1.0',
    'summary': 'This module enables subscription for Products',
    "author": "Silver Touch Technologies Limited",
    "website": "https://www.silvertouch.com",
    'category': 'Sales',
    'depends': [
        'sale_management','product','stock','sale','kg_success_pack','kg_estimation','kg_curr_conv','kg_contracts',
    ],
    'data': [
        "data/email_template.xml",
        "data/data.xml",
        "data/notification_cron.xml",
        "data/close_reason_data.xml",
        "security/ir.model.access.csv",
        "security/contract_security.xml",
        "views/subscription_views.xml",
        'views/product_views.xml',
        "views/sale_views.xml",
        "views/ir_cron.xml",
        "views/close_reason.xml",
        "views/res_config.xml",
        "views/project_contract_free_support_view.xml",
        "views/menu.xml",
        "views/contract_order_menu.xml",
        "views/project_contract_request_views.xml",
        "views/free_support_dahboard.xml",
        "wizard/close_reason_wizard.xml",
        "wizard/confirm_cancel_invoice_wizard_views.xml",
        "wizard/amc_analysis_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            'sttl_sale_subscription/static/src/js/contract_order_dashboard.js',
            'sttl_sale_subscription/static/src/xml/contract_order_dashboard.xml',
            'sttl_sale_subscription/static/src/js/free_support_dashboard.js',
            'sttl_sale_subscription/static/src/xml/free_support_dashboard.xml',
        ]
    },
    'license':'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
    'images': ['static/description/banner.png'],
}
