from . import hr_contract
from . import hr_employee
from . import training_course
from . import employee_training_form
from . import hr_payslip
from . import hr_leave
from . import hr_leave_allocation
from . import hr_religion
from . import annual_leave_transfer
from . import gratuity_settlement
from . import leave_encashment
from . import hr_attendance
from . import job_grade
from . import hr_job
from . import employee_certificates
from . import res_config_settings
