{
    'name': 'Kg Hr',
    'version': '17.0.1.0.0',
    'summary': 'Customizations for employee',
    'sequence': 100,
    'description': 'This module enhances employee functionalities.',
    'author': 'Klystron Global',
    'maintainer': 'Bebisha CP',
    'license': 'LGPL-3',

    'depends': ['base', 'hr', 'hr_payroll', 'mail','kg_document_expiry', 'hr_gratuity_settlement',
                'deduction_management','hr_holidays','hr_attendance'],
    'data': [
        'data/ir_cron_views.xml',
        'data/payroll_rule_views.xml',
        'data/sequence_views.xml',
        'security/ir.model.access.csv',
        'reports/payslip_printout_template.xml',
        'views/employee_views.xml',
        'views/hr_contract_views.xml',
        'views/res_config_settings_views.xml',
        'views/air_ticket.xml',
        'views/airticket_master_views.xml',
        'views/hr_attendance_views.xml',
        'views/hr_payslip_views.xml',
        'wizards/payslip_report_wizard_views.xml',
        'wizards/sif_reoport_wizrd.xml',
        'wizards/menu.xml',
    ],
    'installable': True,
    'application': True,
}
