from . import res_config_settings
from . import processing_documents
from . import sale_order
from . import sale_qtn_line
from . import res_partner
from . import account_payment_term
from . import res_partner_bank
from . import sale_order_line
from . import supplier_category
from . import divisions
from . import sale_terms_conditions
from . import purchase_order
from . import package_list
from . import delivery_terms
from . import product_template
from . import material_requisition
from . import mrp_production
from . import stock_move
from . import sale_report
from . import account_move_line

