# -*- coding: utf-8 -*-
{
    'name': "KG Mashirah Oil HRMS",

    "summary": "Customization for Employee, Attendance, Contract, Payroll and Timeoff Module",
    "version": "17.0.1.0.0",
    'category': 'Employee, Attendance, Contract, Payroll and Timeoff',
    'author': "Klystron Global",
    'maintainer': "SHARMI SV",
    "license": "OPL-1",
    'website': 'https://www.klystronglobal.com',
    # any module necessary for this one to work correctly
    'depends': ['base', 'hr', 'mail', 'kg_mashirah_oil_purchase', 'hr_contract', 'hr_payroll', 'hr_holidays',
                'kg_masirah_oil_overtime', 'hr_expense', 'sign'],
    'data': [
        'security/ir.model.access.csv',
        'security/employee_security_rule.xml',

        'data/paper_format.xml',
        'data/sequence.xml',
        'data/gratuity_settlement_sequence.xml',
        'data/activity.xml',
        'data/hr_salary_rule.xml',
        'data/hr_leave_type.xml',
        'data/hr_religion_data.xml',
        'data/expiry_notification_template.xml',
        'data/notification_cron.xml',

        'report/gratuity_report.xml',
        'report/experience_certificate.xml',
        'report/experience_certificate_with_seq.xml',
        'report/salary_transfer.xml',
        'report/salary_transfer_with_seq.xml',
        'report/employee_status_with_seq.xml',
        'report/to_whom_it_may_concern.xml',
        'report/to_whom_it_may_concern_with_seq.xml',
        'report/leave_application.xml',
        'report/kg_payslip.xml',
        'report/employee_training_report.xml',
        'report/report.xml',

        'wizard/payslip_report_wizard_views.xml',
        'wizard/menu.xml',

        'views/leave_encashment.xml',
        'views/gratuity_settlement_views.xml',
        'views/res_partner_bank_views.xml',
        'views/hr_employee_views.xml',
        'views/training_course.xml',
        'views/hr_contract_views.xml',
        'views/employee_training_form_views.xml',
        'views/hr_payslip_views.xml',
        'views/hr_religion_views.xml',
        'views/annual_leave_transfer_views.xml',
        'views/hr_leave_views.xml',
        'views/employee_certificate_view.xml',
        'views/hr_attendance_view.xml',
        'views/hr_employee_report_views.xml',
        'views/hr_salary_attachment.xml',
        'views/hr_payroll_reporting_views.xml',
        'views/hr_leave_reporting_views.xml',
        'views/hr_job_view.xml',
        'views/job_grade_view.xml',
        'views/res_config_settings_views.xml',
    ]
}
